### ISSUE TITLE
[Join Request]

### ISSUE THREAD

**Issue by ColTelford** [BSData/whfb-6th-edition#2]
Please can I request Write Access to this Repository

**Comment by amis92** [comment]
I'll just link it for my own sanity: https://github.com/BSData/whfb/issues/277

Well sure, it seems the repo already exists for some reason 🤷‍♂️

Feel free to rule in this repo.

**Comment by amis92** [comment]
There you go: https://github.com/BSData/whfb-6th-edition/invitations

**Comment by OftKilted** [comment]
I recommend that we keep whfb in the same repo.

**Comment by amis92** [comment]
I'll remove the https://github.com/BSData/whfb-6th-edition repo, then. If any of the current contributors want to actually develop 6th edition files, you can do so with @OftKilted 's help at https://github.com/BSData/whfb
- @ColTelford 
- @polkowskijakub 
- @Profi90 

I'll archive this repository. Please continue further discussions on https://github.com/BSData/whfb
